version: '3.6'

services:
  shopware_mysql:
    container_name: sw-mysql
    image: rindevich/mysql-8:latest
    volumes:
      - ./db:/home/db:cached
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: shopware
      MYSQL_INNODB_BUFFER_POOL_SIZE: "3G"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_GENERAL_LOG: 0
      MYSQL_QUERY_CACHE_SIZE: 64M
    networks:
      - internal

  shopware_server:
    container_name: sw-server
    image: rindevich/php7.2:latest
    volumes:
      - ./shopware:/var/www/shopware:cached
      - ./containers/php7/server-apache2-vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
    links:
      - shopware_mysql:mysql
      - shopware_redis:redis
      - shopware_smtp:smtp
    environment:
      TERM: xterm
      PHP_XDEBUG_ENABLED: 1
    ports:
      - "80:80"
    networks:
      - internal

  shopware_redis:
    container_name: sw-redis
    image: webhippie/redis:latest
    ports:
      - 6379:6379
    networks:
      - internal

  shopware_smtp:
    container_name: sw-smtp
    image: mailhog/mailhog

networks:
  internal:
    driver_opts:
      internal: "true"
      driver: bridge