version: '3.6'

services:
  shopware5.4_mysql:
    container_name: sw5.4-mysql
    image: wodby/mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: shopware
      MYSQL_INNODB_BUFFER_POOL_SIZE: "3G"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_GENERAL_LOG: 0
      MYSQL_QUERY_CACHE_SIZE: 64M
    ports:
      - 3366:3306
    volumes:
      - ./db:/home/db:cached
    networks:
      - internal

  shopware5.4_server:
    container_name: sw5.4-server
    image: rindevich/php:7.0
    volumes:
      - ./shopware:/var/www/shopware:cached
      - ./containers/php7/server-apache2-vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
    links:
      - shopware5.4_mysql:mysql
      - shopware5.4_redis:redis
      - shopware5.4_smtp:smtp
      - shopware5.4_esearch:esearch
    environment:
      TERM: xterm
      PHP_XDEBUG_ENABLED: 1
    ports:
      - 80:80
    networks:
      - internal

  shopware5.4_redis:
    container_name: sw5.4-redis
    image: webhippie/redis:latest
    ports:
      - 6379:6379
    networks:
      - internal

  shopware5.4_smtp:
    container_name: sw5.4-smtp
    image: mailhog/mailhog

  shopware5.4_esearch:
    container_name: sw5.4-esearch
    image: elasticsearch:5-alpine
    volumes:
      - ./containers/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      TERM: xterm
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - internal

networks:
  internal:
    driver_opts:
      internal: "true"
      driver: bridge